#cluster endpoint for the controle plane

output "cluster_endpoint" {
    description  = "endpoint for EKS CONTROLE PLANE"
    value = module.eks.cluster_endpoint
}

# get the security group ids attached to the cluster control plane
output "cluster_security_group_id" {
    description  = "security group ids attached to the cluster control plane"
    value = module.eks.cluster_security_group_id
}

#k8s cluster will output the cube config file. we can use this cube config file to pass
# it to the k8s module to spin up deployments, pods, services on the eks cluster
output "kubectl_config" {
    description  = "kubectl config as generated by the module"
    value = module.eks.kubecconfig
}

output "config_map_aws_auth" {
    description  = "A kubernetes config to authenticate to this EKS cluster"
    value = module.eks.config_map_aws_auth
}

# output "region" {
#     description = "AWS region"
#     value = var.region
# }

